apiVersion: v1
entries:
  httpserver:
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2022-12-19T20:28:20.298941+08:00"
    description: A Helm chart for Kubernetes
    digest: 0cf8d23550827dfba9ea1a7054e70c2a84f4441c1595578cec247b8297608944
    name: httpserver
    type: application
    urls:
    - http://www.example.com/httpserver-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-19T20:28:20.298423+08:00"
