apiVersion: v1
kind: Namespace
metadata:
  name:  cloudnative

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpsvc
  namespace: cloudnative
  labels:
    app: httpsvc
data:
  serverPort: "8080"
  version: "1.0.0"
  logPath: "/tmp/httpsvc/logs"
  profile: "PROD"

---
apiVersion: v1
kind: Secret
metadata:
  name: aliyun-private-registry
  namespace: cloudnative
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1ob25na29uZy5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJ4eWFuZzA5MTdAcXEuY29tIiwicGFzc3dvcmQiOiJ5YW5neGluMDkxNyIsImVtYWlsIjoieHlhbmcwOTE3QHFxLmNvbSIsImF1dGgiOiJlSGxoYm1jd09URTNRSEZ4TG1OdmJUcDVZVzVuZUdsdU1Ea3hOdz09In19fQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpsvc-deployment
  namespace: cloudnative
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpsvc
  template:
    metadata:
      labels:
        app: httpsvc
    spec:
      containers:
        - name: httpsvc
          image: registry.cn-hongkong.aliyuncs.com/yangxin/httpserver:0.0.3
          env:
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: httpsvc
                key: serverPort
          - name: VERSION
            valueFrom:
              configMapKeyRef:
                name: httpsvc
                key: version
          - name: LOG_PATH
            valueFrom:
              configMapKeyRef:
                name: httpsvc
                key: logPath
          - name: PROFILE
            valueFrom:
              configMapKeyRef:
                name: httpsvc
                key: profile
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          # 日志写入临时文件
          volumeMounts:
            - name: logs
              mountPath: /tmp/httpsvc/logs
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 1
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 1
            initialDelaySeconds: 3
      imagePullSecrets:
      - name: aliyun-private-registry
      restartPolicy: Always
      volumes:
      - name: logs
        emptyDir: {}
            
---
apiVersion: v1
kind: Service
metadata:
  name: httpsvc-gateway
  namespace: cloudnative
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  selector:
    app: httpsvc

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: cloudnative
spec:
  acme:
    email: xyang0917@qq.com
    preferredChain: "ISRG Root X1"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpsvc
  namespace: cloudnative
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: fstar.cc
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: httpsvc-gateway
                port:
                  number: 80
  tls:
    - hosts:
        - fstar.cc
      secretName: httpsvc-tls